#───────────────────────────────────────────────────────────────────────────────────────────────
#─██████████████─██████████████─██████──────────██████─██████████████─██████████─██████████████─
#─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██████████──██░░██─██░░░░░░░░░░██─██░░░░░░██─██░░░░░░░░░░██─
#─██░░██████████─██░░██████░░██─██░░░░░░░░░░██──██░░██─██░░██████████─████░░████─██░░██████████─
#─██░░██─────────██░░██──██░░██─██░░██████░░██──██░░██─██░░██───────────██░░██───██░░██─────────
#─██░░██─────────██░░██──██░░██─██░░██──██░░██──██░░██─██░░██████████───██░░██───██░░██─────────
#─██░░██─────────██░░██──██░░██─██░░██──██░░██──██░░██─██░░░░░░░░░░██───██░░██───██░░██──██████─
#─██░░██─────────██░░██──██░░██─██░░██──██░░██──██░░██─██░░██████████───██░░██───██░░██──██░░██─
#─██░░██─────────██░░██──██░░██─██░░██──██░░██████░░██─██░░██───────────██░░██───██░░██──██░░██─
#─██░░██████████─██░░██████░░██─██░░██──██░░░░░░░░░░██─██░░██─────────████░░████─██░░██████░░██─
#─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██──██████████░░██─██░░██─────────██░░░░░░██─██░░░░░░░░░░██─
#─██████████████─██████████████─██████──────────██████─██████─────────██████████─██████████████─
#───────────────────────────────────────────────────────────────────────────────────────────────

Motd:
  enable: true
  motd:
  - "        &8&l-** &3&lYourNetwork&8&l**-"
  - "        &B&LHex colors suport!"

Chat:
  ChatFormat: "%prefix%%suffix% %player% %suffix% &8» &7%message%"

#─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
#─██████████████─██████──────────██████─██████████████─██████████─██████████████─██████████████─██████████████─██████──────────██████─
#─██░░░░░░░░░░██─██░░██████████──██░░██─██░░░░░░░░░░██─██░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██████████████░░██─
#─██░░██████░░██─██░░░░░░░░░░██──██░░██─██████░░██████─████░░████─██░░██████████─██░░██████░░██─██░░██████░░██─██░░░░░░░░░░░░░░░░░░██─
#─██░░██──██░░██─██░░██████░░██──██░░██─────██░░██───────██░░██───██░░██─────────██░░██──██░░██─██░░██──██░░██─██░░██████░░██████░░██─
#─██░░██████░░██─██░░██──██░░██──██░░██─────██░░██───────██░░██───██░░██████████─██░░██████░░██─██░░██████░░██─██░░██──██░░██──██░░██─
#─██░░░░░░░░░░██─██░░██──██░░██──██░░██─────██░░██───────██░░██───██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██──██░░██──██░░██─
#─██░░██████░░██─██░░██──██░░██──██░░██─────██░░██───────██░░██───██████████░░██─██░░██████████─██░░██████░░██─██░░██──██████──██░░██─
#─██░░██──██░░██─██░░██──██░░██████░░██─────██░░██───────██░░██───────────██░░██─██░░██─────────██░░██──██░░██─██░░██──────────██░░██─
#─██░░██──██░░██─██░░██──██░░░░░░░░░░██─────██░░██─────████░░████─██████████░░██─██░░██─────────██░░██──██░░██─██░░██──────────██░░██─
#─██░░██──██░░██─██░░██──██████████░░██─────██░░██─────██░░░░░░██─██░░░░░░░░░░██─██░░██─────────██░░██──██░░██─██░░██──────────██░░██─
#─██████──██████─██████──────────██████─────██████─────██████████─██████████████─██████─────────██████──██████─██████──────────██████─
#─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

AntiSpam:
  time: 3
  message: "&b\u27bd &cNo puedes hacer spam en el servidor espera &e&l%time% &cpara escribir."


Msg:
  send: '&c&l(!) &8&l[&e&lTu &7-> &b%player%&8&l]&7'
  received: '&c&l(!) &8&l[&b%player% &7-> &e&lTu&8&l]&7'
SocialSpy:
  msg: '&b&lEspia &8&l[&e&l%tarjet% &7-> &b%player%&8&l]&7 %msg%'




