name: HyperCore
version: 1.0.0
authors: [bixgamer707,xlsm4]
main: me.bixgamer707.hypercore.HyperCore
softdepend: [PlaceholderAPI]
commands:
  hypercore:
    description: Main Command
    aliases: [hc]
  clearchat:
    description: Remove chat from the entire server!
    aliases: [cc]
  msg:
    description: Message private!
    aliases: [tell]
  socialspy:
    description: View private messages the other players
    alises: [ss]
  broadcast:
    description: Send a message to the whole server!
    aliases: [b,bd]
  gamemode:
    description: Switch between the different gamemode types!
    aliases: [gm]
  gamemode0:
    description: Change gamemode to Survival
    aliases: [gm0,gms]
  gamemode1:
    description: Change gamemode to Creative
    aliases: [ gm1,gmc ]
  gamemode2:
    description: Change gamemode to Adventure
    aliases: [ gm2,gma ]
  gamemode3:
    description: Change gamemode to Spectator
    aliases: [ gm3,gmst ]
  fly:
    description: Fly but if permission required
    aliases: [f]